[package]
description = "A Blazingly fast JavaScript runtime"
name = "lunos"
version = "0.2.0"
edition = "2021"
authors = ["Thoq"]
license = "MIT"

[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.5.2", features = ["full", "server"] }
hyper-util = { version = "0.1.10", features = ["full", "server", "tokio"] }
javascriptcore-sys = "0.0.6"
tokio = { version = "1.42.0", features = ["full"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.release.build-override]
opt-level = 3

[profile.release.package."*"]
opt-level = 3
